[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "eventlog2"
version = "0.1.0"
description = "HTML log viewer"
requires-python = ">=3.10"
dependencies = [
    "flask",
    "waitress",
    "docopt",
    "docutils",
]

[project.scripts]
eventlog2 = "eventlog2.__main__:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["eventlog2*"]

[tool.setuptools.package-data]
eventlog2 = [
    "templates/**/*.html",
    "static/**/*.js",
    "static/**/*.css",
    "static/**/*.html",
]
